import "./globals.css";

import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout;